package proyecto1_arqui1_gui;

import javax.swing.JOptionPane;
import FileManager.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import ARManalyzers.*;
import Simulator.*;

/**
 *
 * @author Daniel
 */
public class mainWindow extends javax.swing.JFrame {
    private String _actualPath; //indica el path del archivo que actualmente está trabajando
    DataTables dt;
    Simulacion sim;
    private boolean _archivoCompilado;
    
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        this._actualPath = "";
        dt = new DataTables();
        dt.initDataTable();
        dt.initInstructionTable();
        dt.initRegisterTable();
        sim = new Simulacion();
        this._archivoCompilado = false;
        initComponents();
    }
    
    private void guardarComoFileChooser(String textoAGuardar)
    {
        JFrame parentFrame = new JFrame();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como...");
        int userSelection = fileChooser.showSaveDialog(parentFrame);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (fileToSave.getAbsolutePath().endsWith(".armv4") &&
                !File_TXT.verifyFilenameExists(fileToSave.getAbsolutePath())) {
                        this._actualPath = fileToSave.getAbsolutePath();
                try {
                    File_TXT.writeText(fileToSave.getAbsolutePath(), textoAGuardar);
                } catch (IOException ex) {
                    Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                    JOptionPane.showMessageDialog(this, "¡Archivo guardado"
                  + " con éxito!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                        
            }else if (!fileToSave.getAbsolutePath().endsWith(".armv4") &&
                !File_TXT.verifyFilenameExists(fileToSave.getAbsolutePath() + ".armv4")){
                this._actualPath = fileToSave.getAbsolutePath() + ".armv4";
                try {
                    File_TXT.writeText(fileToSave.getAbsolutePath(), textoAGuardar);
                } catch (IOException ex) {
                    Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                    JOptionPane.showMessageDialog(this, "¡Archivo guardado"
                  + " con éxito!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            } else{
                 JOptionPane.showMessageDialog(this, "¡Ya existe archivo "
                  + "con ese nombre!",
                "Guardar como", JOptionPane.WARNING_MESSAGE);
            }
        }
    }// fin del método
    
    private void guardarSinFileChooser(String textoAGuardar)
    {
        try {
            File_TXT.writeText(this._actualPath, textoAGuardar);
        } catch (IOException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(this, "¡Archivo actualizado y"
                    + " guardado!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    
    }// fin del método
    
    private void cargarFileChooser()
    {
        JFrame parentFrame = new JFrame();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Abrir...");
        String texto = "";
        int userSelection = fileChooser.showOpenDialog(parentFrame);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToLoad = fileChooser.getSelectedFile();
            try {
                if(fileToLoad.getAbsolutePath().endsWith(".armv4")){
                    this._actualPath = null;
                    editorTextPane.setText("");
                    texto = File_TXT.readText(fileToLoad.getAbsolutePath());
                    this._actualPath = fileToLoad.getAbsolutePath();
                    editorTextPane.setText(texto);
                    String path = MessageInterpreter.showActualPath(_actualPath);
                    jTextArea1.setText(path);
                }else{
                    JOptionPane.showMessageDialog(this, "¡Formato de archivo"
                  + " no es compatible!",
                "Cargar", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }    
        }
        
    }// fin del método
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        LBL_virtualMemory = new javax.swing.JLabel();
        LBL_editor = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        GUI_tablaRegistros = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        GUI_tablaDatos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        GUI_tablaInstrucciones = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        editorTextPane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LBL_fondo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARMv4 Compiler");
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        LBL_virtualMemory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_virtualMemory.setForeground(new java.awt.Color(255, 255, 255));
        LBL_virtualMemory.setText("Virtual Memory");

        LBL_editor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_editor.setForeground(new java.awt.Color(255, 255, 255));
        LBL_editor.setText("Editor");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        GUI_tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            dt.getTablaRegistros(),
            new String [] {
                "Register", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int col) {
                if (col == 0 && col == 1) {
                    return true;
                } else {
                    return false;
                }
            }
        });
        GUI_tablaRegistros.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(GUI_tablaRegistros);

        jTabbedPane1.addTab("Registers", jScrollPane2);

        GUI_tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            dt.getTablaDatos(),
            new String [] {
                "Address", "Value"
            }
        )    {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int col) {
                if ( col == 1) {
                    return true;
                } else {
                    return false;
                }
            }
        });
        GUI_tablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(GUI_tablaDatos);

        jTabbedPane1.addTab("Data", jScrollPane3);

        GUI_tablaInstrucciones.setModel(new javax.swing.table.DefaultTableModel(
            dt.getTablaInstrucciones(),
            new String [] {
                "Address", "Instruction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int col) {
                if ( col == 1 && col == 0) {
                    return true;
                } else {
                    return false;
                }
            }
        });
        GUI_tablaInstrucciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(GUI_tablaInstrucciones);

        jTabbedPane1.addTab("Instructions", jScrollPane4);

        editorTextPane.setEditorKit(new javax.swing.text.StyledEditorKit());
        editorTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(editorTextPane);
        TextLineNumber tln = new TextLineNumber( editorTextPane );
        TextWordsColor twc = new TextWordsColor(editorTextPane);
        LinePainter painter = new LinePainter(editorTextPane);
        jScrollPane5.setRowHeaderView( tln );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(MessageInterpreter.initMensaje(""));
        jScrollPane1.setViewportView(jTextArea1);

        LBL_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_arqui1_gui/fondo2.jpg"))); // NOI18N

        jMenu2.setMnemonic(KeyEvent.VK_N);
        jMenu2.setText("File");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Nuevo");
        jMenuItem1.setText("New");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        KeyStroke ctrlNKeyStroke = KeyStroke.getKeyStroke("control N");
        jMenuItem1.setAccelerator(ctrlNKeyStroke);
        jMenu2.add(jSeparator3);

        jMenuItem3.setMnemonic(KeyEvent.VK_O);
        jMenuItem3.setText("Open");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        KeyStroke ctrlOKeyStroke = KeyStroke.getKeyStroke("control O");
        jMenuItem3.setAccelerator(ctrlOKeyStroke);
        jMenu2.add(jSeparator5);

        jMenuItem2.setText("Save As ...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        KeyStroke ctrlAltSKeyStroke = KeyStroke.getKeyStroke("control alt S");
        jMenuItem2.setAccelerator(ctrlAltSKeyStroke);

        jMenuItem8.setMnemonic(KeyEvent.VK_S);
        jMenuItem8.setText("Save");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);
        KeyStroke ctrlSKeyStroke = KeyStroke.getKeyStroke("control S");
        jMenuItem8.setAccelerator(ctrlSKeyStroke);
        jMenu2.add(jSeparator4);
        jMenu2.add(jSeparator1);

        jMenuItem10.setText("Close");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        KeyStroke ctrlAltQKeyStroke = KeyStroke.getKeyStroke("control alt Q");
        jMenuItem10.setAccelerator(ctrlAltQKeyStroke);

        jMenuItem4.setMnemonic(KeyEvent.VK_Q);
        jMenuItem4.setText("Quit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        KeyStroke ctrlQKeyStroke = KeyStroke.getKeyStroke("control Q");
        jMenuItem4.setAccelerator(ctrlQKeyStroke);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Run");

        jMenuItem5.setText("Go");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);
        KeyStroke ctrlRKeyStroke = KeyStroke.getKeyStroke("control R");
        jMenuItem5.setAccelerator(ctrlRKeyStroke);

        jMenuItem7.setText("Stop");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);
        KeyStroke ctrlTKeyStroke = KeyStroke.getKeyStroke("control T");
        jMenuItem7.setAccelerator(ctrlTKeyStroke);

        jMenuItem6.setText("Assembly");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);
        KeyStroke ctrlAKeyStroke = KeyStroke.getKeyStroke("control A");
        jMenuItem6.setAccelerator(ctrlAKeyStroke);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem11.setText("About");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBL_editor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBL_virtualMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LBL_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_editor)
                    .addComponent(LBL_virtualMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LBL_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // METODO NO SE USA
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here: Archivo < Nuevo
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea continuar? "
                + "Cambios que no son guardados se borrarán", 
                "Nuevo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (JOptionPane.YES_OPTION == respuesta){
            this.editorTextPane.setText("");
            this._actualPath = "";
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here: Archivo < Guardar como...
        String textoAGuardar = editorTextPane.getText();
        guardarComoFileChooser(textoAGuardar);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here: Archivo < Salir
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir? "
                + "Cambios que no son guardados se borrarán", 
                "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (JOptionPane.YES_OPTION == respuesta){
            setVisible(false); //you can't see me!
            dispose(); //Destroy the JFrame object
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // TODO add your handling code here: Run < Go
            
            dt.updateDataFromGUITablaDatos(GUI_tablaDatos);
            String[][] tmp =  dt.getTablaDatosSTR(dt.getTablaDatos(), 256);
            
            if (this._actualPath.isEmpty() || !this._archivoCompilado){
                JOptionPane.showMessageDialog(this, "¡No se ha compilado el archivo!",
                "Error", JOptionPane.ERROR_MESSAGE);
                String msj = MessageInterpreter.mensajeExecution("No se ha compilado ningún archivo.");
                jTextArea1.setText(msj);
            } else if (!dt.verifySintaxis(tmp)) {
                //System.out.println("ERROR");
                String salida = MessageInterpreter.mensajeExecution("Existen errores léxicos"
                        + " en memoria de datos");
                jTextArea1.setText(salida);
                JOptionPane.showMessageDialog(this, "¡Revise la memoria de datos,"
                  + " existen errores léxicos!",
                "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
                String mensaje = sim.start(tmp);    // inicia el run!!!
                String salida = MessageInterpreter.mensaje(mensaje);
                if (mensaje.equals("El programa ha sido simulado con éxito")){
                    salida += MessageInterpreter.mensajeExecution("El tiempo de ejecución fue de " 
                        + sim.getTime() + " ns.");
                //sim.getMem().get(mensaje);
                
                // TO DO: ACTUALIZAR TABLAS GUI
                    dt.setTablaDatos(tmp);
                    //dt.printTablaDatos();
                    dt.setTablaInstrucciones(fillInstructionGUI());
                    dt.setTablaRegistros(fillRegisterGUI());
                // ACTUALIZA GUI
                    dt.updateTableValues(GUI_tablaDatos, 256, 2, dt.getTablaDatos());
                    dt.updateTableValues(GUI_tablaInstrucciones, 256, 2, dt.getTablaInstrucciones());
                    dt.updateTableValues(GUI_tablaRegistros, 16, 2, dt.getTablaRegistros());
                }
            jTextArea1.setText(salida);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    private Object[][] fillDataGUI()
    {
        Object[][] tmpDatos = new Object[256][2];
        int contador = 0;
        String intStr, strHex, hex = null;
        for (int i = 0; i < 256; i++){
            for (int j = 0; j < 2; j++){
                intStr = Integer.toString(contador);
                strHex = Long.toHexString((i*4)+1024);
                hex = String.format("%8s", strHex).replace(' ', '0');
                if (j == 0) {
                   tmpDatos[i][j] = "0x" + hex; 
                }else{
                    if (sim.getMem().get(hex) == null) 
                        tmpDatos[i][j] =  "0x" + "00000000";
                    else
                        tmpDatos[i][j] =  "0x" + sim.getMem().get(hex);
                }
            }
            contador += 4;
        }
        return tmpDatos;
    }
    
    private Object[][] fillInstructionGUI()
    {
        Object[][] tmp = new Object[256][2];
        int contador = 0;
        String intStr, strHex, hex = null;
        for (int i = 0; i < 256; i++){
            for (int j = 0; j < 2; j++){
                intStr = Integer.toString(contador);
                strHex = Long.toHexString(i*4);
                hex = String.format("%8s", strHex).replace(' ', '0');
                if (j == 0) {
                   tmp[i][j] = "0x" + hex; 
                }else{
                    if (sim.getProg().get(hex) == null) 
                        tmp[i][j] =  "0x" + "00000000";
                    else
                        tmp[i][j] =  "0x" + sim.getProg().get(hex);
                }
            }
            contador += 4;
        }
        return tmp;
    }
    
    private Object[][] fillRegisterGUI()
    {
        Object[][] tmp = new Object[16][2];
        String intStr, strBin, bin = null;
        for (int i = 0; i < 16; i++){
            for (int j = 0; j < 2; j++){
                intStr = Integer.toString(i);
                strBin = Long.toBinaryString(i);
                bin = String.format("%4s", strBin).replace(' ', '0');
                //System.out.println("BINARIOS: " + bin);
                if (j == 0) {
                    if (i == 13) {
                        tmp[i][j] = "R" + i + "  (SP)"; 
                    }else if (i == 14) {
                        tmp[i][j] = "R" + i + "  (LR)"; 
                    }else if (i == 15) {
                        tmp[i][j] = "R" + i + "  (PC)"; 
                    }else
                        tmp[i][j] = "R" + i; 
                }else{
                    if (sim.getReg().get(bin) == null) 
                        tmp[i][j] = "0x"+ "00000000";
                    else
                        tmp[i][j] = "0x"+ sim.getReg().get(bin);
                }
            }
        }
        return tmp;
    }
    
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here: Archivo < Abrir
        cargarFileChooser();
        MessageInterpreter.showActualPath(_actualPath);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // NO SE USA METODO
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here: Archivo < Cerrar
        String textoAGuardar = "";
        if (this.editorTextPane.getText().isEmpty() && this._actualPath.isEmpty())
        {
            // El texto está vacío y no se ha abierto ni guardado como...
            this.editorTextPane.setText("");
            this._archivoCompilado = false;
        }else if(!this.editorTextPane.getText().isEmpty() && this._actualPath.isEmpty())
        {
           // El texto NO está vacío y se ha abierto o guardado como... 
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea guardar "
                + "los cambios?\n"
                + "(Cambios que no son guardados se borrarán)", 
                "Cerrar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (JOptionPane.YES_OPTION == respuesta){
                textoAGuardar = editorTextPane.getText();
                guardarComoFileChooser(textoAGuardar);
                this.editorTextPane.setText("");
                String path = MessageInterpreter.showActualPath("No current file");
                jTextArea1.setText(path);
                this._archivoCompilado = false;
            }
        }else {
            textoAGuardar = editorTextPane.getText();
            guardarSinFileChooser(textoAGuardar);
            JOptionPane.showMessageDialog(this, "¡Archivo actualizado y"
                    + " guardado!", "Cerrar", JOptionPane.INFORMATION_MESSAGE);
            this.editorTextPane.setText("");
            String path = MessageInterpreter.showActualPath("No current file");
            jTextArea1.setText(path);
            this._archivoCompilado = false;
        }
        MessageInterpreter.showActualPath(_actualPath);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here: Archivo < Guardar
        System.out.println(this._actualPath);
        String textoAGuardar;
        if(!this._actualPath.isEmpty())
        {
           // El texto NO está vacío y se ha abierto o guardado como... 
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea actualizar "
                + "los cambios?\n"
                + "(Cambios que no son guardados se borrarán)", 
                "Guardar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (JOptionPane.YES_OPTION == respuesta){
                textoAGuardar = editorTextPane.getText();
                guardarSinFileChooser(textoAGuardar);
            }
        }else{
            textoAGuardar = editorTextPane.getText();
            guardarComoFileChooser(textoAGuardar);
        }
        MessageInterpreter.showActualPath(_actualPath);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here: Run < Stop
        //String aa = GUI_tablaDatos.getValueAt(0,1).toString();
        //System.out.println("VALOR tabla: " + aa);
        //dt.updateDataFromGUITablaDatos(GUI_tablaDatos);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here: Run < Assembly
        if(this._actualPath.isEmpty())
        {
           JOptionPane.showMessageDialog(this, "¡No se ha cargado ningún archivo"
                   + " .armv4!",
                "Atención", JOptionPane.ERROR_MESSAGE);
            this._archivoCompilado = false;
            String msj = MessageInterpreter.mensajeAssembly("No se ha cargado ningún archivo.");
            jTextArea1.setText(msj);
        }else{
            try{
                // El texto NO está vacío y se ha abierto o guardado como... 
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea actualizar "
                    + "los cambios antes de ensamblar?\n"
                    + "(Cambios que no son guardados se borrarán)", 
                    "Guardar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                String textoAGuardar = "";
                if (JOptionPane.YES_OPTION == respuesta){
                    textoAGuardar = editorTextPane.getText();
                    guardarSinFileChooser(textoAGuardar);
                    this._archivoCompilado = true;
                    Grammar.ExecuteGrammar(this._actualPath);
                }
            } catch(Exception e){
                ModuloError.insertError("No se pudo realizar el ensamblaje.");
            }
            String msj = MessageInterpreter.mensajeAssembly(ModuloError.getError());
            jTextArea1.setText(msj);
            ModuloError.resetError();
        }
        MessageInterpreter.showActualPath(_actualPath);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here: Help < About
        JOptionPane.showMessageDialog(this, MessageInterpreter.aboutMessage()
                , "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GUI_tablaDatos;
    private javax.swing.JTable GUI_tablaInstrucciones;
    private javax.swing.JTable GUI_tablaRegistros;
    private javax.swing.JLabel LBL_editor;
    private javax.swing.JLabel LBL_fondo;
    private javax.swing.JLabel LBL_virtualMemory;
    private javax.swing.JTextPane editorTextPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    }