
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package ARManalyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STR = 22;
  public static final int SBC = 8;
  public static final int LDR = 23;
  public static final int BNE = 29;
  public static final int MVN = 19;
  public static final int ORR = 12;
  public static final int REGISTER = 32;
  public static final int CMP = 10;
  public static final int CMN = 11;
  public static final int BGT = 30;
  public static final int B = 26;
  public static final int SEMICOLON = 34;
  public static final int AND = 2;
  public static final int LSL = 14;
  public static final int ADDRESS = 40;
  public static final int EOR = 3;
  public static final int MOV = 13;
  public static final int EOF = 0;
  public static final int ASR = 15;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int COMA = 33;
  public static final int CLOSEBRACKET = 38;
  public static final int NEWLINE = 36;
  public static final int ADD = 6;
  public static final int ADC = 7;
  public static final int NUMBER = 39;
  public static final int MLA = 21;
  public static final int BL = 27;
  public static final int BLT = 31;
  public static final int RSC = 9;
  public static final int RSB = 5;
  public static final int OPENBRACKET = 37;
  public static final int RRX = 16;
  public static final int BIC = 18;
  public static final int ROR = 17;
  public static final int LDRB = 25;
  public static final int TEXT = 35;
  public static final int STRB = 24;
  public static final int SUB = 4;
  public static final int BEQ = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "EOR",
  "SUB",
  "RSB",
  "ADD",
  "ADC",
  "SBC",
  "RSC",
  "CMP",
  "CMN",
  "ORR",
  "MOV",
  "LSL",
  "ASR",
  "RRX",
  "ROR",
  "BIC",
  "MVN",
  "MUL",
  "MLA",
  "STR",
  "LDR",
  "STRB",
  "LDRB",
  "B",
  "BL",
  "BEQ",
  "BNE",
  "BGT",
  "BLT",
  "REGISTER",
  "COMA",
  "SEMICOLON",
  "TEXT",
  "NEWLINE",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "NUMBER",
  "ADDRESS"
  };
}

